#Kind and metadata

apiVersion: v1
kind: Service
metadata:
  name: sre-log-analyser

#Spec

spec:
  selector:
    app: sre-log-analyser
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800